## PySpark
### dodawanie i usuwanie kolumn

In [14]:
# utworzenie data frame (zapytanie w wielu wierszach)

df_person = spark.sql("""
    SELECT p.BusinessEntityID, FirstName, Lastname, MiddleName, Gender, SalariedFlag, VacationHours 
    FROM AdventureWorks.Person_Person AS p
    JOIN AdventureWorks.HumanResources_Employee AS e ON e.BusinessEntityID = p.BusinessEntityID 
""")

StatementMeta(, 75d11d09-9d76-4115-83cf-af56a2eeb248, 16, Finished, Available)

In [11]:
df_person.show(5)

StatementMeta(, 75d11d09-9d76-4115-83cf-af56a2eeb248, 13, Finished, Available)

+----------------+---------+--------+----------+------+------------+-------------+
|BusinessEntityID|FirstName|Lastname|MiddleName|Gender|SalariedFlag|VacationHours|
+----------------+---------+--------+----------+------+------------+-------------+
|              65|    Randy|  Reeves|         T|     M|       false|           29|
|              82|     Jack| Creasey|         T|     M|       false|           62|
|             110|      Jun|     Cao|         T|     M|       false|           90|
|             125| Matthias|  Berndt|         T|     M|       false|           94|
|             126|    Jimmy|Bischoff|         T|     M|       false|           96|
+----------------+---------+--------+----------+------+------------+-------------+
only showing top 5 rows

In [15]:
df_person.printSchema()

StatementMeta(, 75d11d09-9d76-4115-83cf-af56a2eeb248, 17, Finished, Available)

root
 |-- BusinessEntityID: integer (nullable = true)
 |-- FirstName: string (nullable = true)
 |-- Lastname: string (nullable = true)
 |-- MiddleName: string (nullable = true)
 |-- Gender: string (nullable = true)
 |-- SalariedFlag: boolean (nullable = true)
 |-- VacationHours: short (nullable = true)

In [16]:
from pyspark.sql.functions import col, concat, lit

# tworzenie dodatkowej kolumny
df_person = df_person.withColumn("FullName", concat(col("FirstName"), lit(" "), col("LastName"))) 

# zmiana typu danych kolumny
df_person = df_person.withColumn("VacationHours",col("VacationHours").cast("Integer"))

df_person.show()
df_person.printSchema()

StatementMeta(, 75d11d09-9d76-4115-83cf-af56a2eeb248, 18, Finished, Available)

+----------------+---------+--------------+----------+------+------------+-------------+--------------------+
|BusinessEntityID|FirstName|      Lastname|MiddleName|Gender|SalariedFlag|VacationHours|            FullName|
+----------------+---------+--------------+----------+------+------------+-------------+--------------------+
|              65|    Randy|        Reeves|         T|     M|       false|           29|        Randy Reeves|
|              82|     Jack|       Creasey|         T|     M|       false|           62|        Jack Creasey|
|             110|      Jun|           Cao|         T|     M|       false|           90|             Jun Cao|
|             125| Matthias|        Berndt|         T|     M|       false|           94|     Matthias Berndt|
|             126|    Jimmy|      Bischoff|         T|     M|       false|           96|      Jimmy Bischoff|
|             130|      Rob|         Caron|         T|     M|       false|           71|           Rob Caron|
|             137|   Anibal|         Sousa|         T|     F|       false|            8|        Anibal Sousa|
|             165|    Chris|       Preston|         T|     M|       false|           76|       Chris Preston|
|             175|     Reed|          Koch|         T|     M|       false|           23|           Reed Koch|
|             181|  Michael|         Hines|         T|     M|       false|           20|       Michael Hines|
|             194|     Fred|       Northup|         T|     M|       false|           47|        Fred Northup|
|             200|    Frank|           Lee|         T|     M|       false|           56|           Frank Lee|
|             201|    Brian|         Lloyd|         T|     M|       false|           55|         Brian Lloyd|
|             213|   Sootha|Charncherngkha|         T|     M|       false|           85|Sootha Charnchern...|
|             214|  Andreas|      Berglund|         T|     M|       false|           84|    Andreas Berglund|
|             240|   Willis|       Johnson|         T|     M|       false|           49|      Willis Johnson|
|             259|      Ben|        Miller|         T|     M|       false|           55|          Ben Miller|
|               8|    Diane|      Margheim|         L|     F|        true|           62|      Diane Margheim|
|              30|   Britta|         Simon|         L|     F|       false|           14|        Britta Simon|
|              51|  Jeffrey|          Ford|         L|     M|       false|           85|        Jeffrey Ford|
+----------------+---------+--------------+----------+------+------------+-------------+--------------------+
only showing top 20 rows

root
 |-- BusinessEntityID: integer (nullable = true)
 |-- FirstName: string (nullable = true)
 |-- Lastname: string (nullable = true)
 |-- MiddleName: string (nullable = true)
 |-- Gender: string (nullable = true)
 |-- SalariedFlag: boolean (nullable = true)
 |-- VacationHours: integer (nullable = true)
 |-- FullName: string (nullable = true)

In [21]:
# zmiana nazwy kolumny
df_person = df_person.withColumnRenamed("BusinessEntityID","ID")

df_person.show(5)

StatementMeta(, 75d11d09-9d76-4115-83cf-af56a2eeb248, 23, Finished, Available)

+---+---------+--------+----------+------+------------+-------------+
| ID|FirstName|Lastname|MiddleName|Gender|SalariedFlag|VacationHours|
+---+---------+--------+----------+------+------------+-------------+
| 65|    Randy|  Reeves|         T|     M|       false|           29|
| 82|     Jack| Creasey|         T|     M|       false|           62|
|110|      Jun|     Cao|         T|     M|       false|           90|
|125| Matthias|  Berndt|         T|     M|       false|           94|
|126|    Jimmy|Bischoff|         T|     M|       false|           96|
+---+---------+--------+----------+------+------------+-------------+
only showing top 5 rows

In [22]:
# skasowanie kolumny
df_person = df_person.drop("FullName")
df_person.show(5)

StatementMeta(, 75d11d09-9d76-4115-83cf-af56a2eeb248, 24, Finished, Available)

+---+---------+--------+----------+------+------------+-------------+
| ID|FirstName|Lastname|MiddleName|Gender|SalariedFlag|VacationHours|
+---+---------+--------+----------+------+------------+-------------+
| 65|    Randy|  Reeves|         T|     M|       false|           29|
| 82|     Jack| Creasey|         T|     M|       false|           62|
|110|      Jun|     Cao|         T|     M|       false|           90|
|125| Matthias|  Berndt|         T|     M|       false|           94|
|126|    Jimmy|Bischoff|         T|     M|       false|           96|
+---+---------+--------+----------+------+------------+-------------+
only showing top 5 rows